### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by atheeraa** [HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch#1]
Hello, Thank you for sharing this code 
I get this error when running train.py

HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E9E535048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Can you please help me solve it?

**Comment by HanGuangXin** [comment]
Hi there. I'm HanGuangXin. Thanks for asking!


In short, this error is related to the 'visdom' package, which is used for visualization. I guess there is something wrong with the server.


Maybe you should run "python -m visdom.server" in command line(cmd) before run train.py.


To be honest, I haven't run into this error. So please let me know if there is any progress!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上6:32
收件人:&nbsp;"HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"<Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch] HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E9E535048&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)) (#1)





 
Hello, Thank you for sharing this code
 I get this error when running train.py
 
HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E9E535048&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
 
Can you please help me solve it?

**Comment by atheeraa** [comment]
Hello HanGuangXin, Thank you for replying, 
I ran the server in another terminal and it seems that it was the issue

However, now it gets stuck at "Setting up a new session..." then stops 

![image](https://user-images.githubusercontent.com/36483740/106882186-38a32480-66bd-11eb-94e3-31f11154f271.png)

This is what the server shows: 
![image](https://user-images.githubusercontent.com/36483740/106882786-ed3d4600-66bd-11eb-975a-f4c75ca543ef.png)

**Comment by HanGuangXin** [comment]
Hi there, I got the same results as you.

You should open "http://localhost:8097/" for visualization results

Note: You should only select “pyGCN visualization” as Environment!

Please let me know if there are any progress!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上6:47
收件人:&nbsp;"HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"<Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"Reverse"<734167802@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch] No connection could be made because the target machine actively refused it (#1)





 
Hello HanGuangXin, Thank you for replying,
 I ran the server in another terminal and it seems that it was the issue
 
However, now it gets stuck at "Setting up a new session..." then stops
 
What do I do? How can I see the visualization of the results?

**Comment by HanGuangXin** [comment]
Hi there, I got the same results as you. You should open "http://localhost:8097/" for visualization results Note: You should only select “pyGCN visualization” as Environment! Please let me know if there are any progress!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上6:47
收件人:&nbsp;"HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch"<Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"Reverse"<734167802@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HanGuangXin/Result-Visualization-of-Graph-Convolutional-Networks-in-PyTorch] No connection could be made because the target machine actively refused it (#1)





 
Hello HanGuangXin, Thank you for replying,
 I ran the server in another terminal and it seems that it was the issue
 
However, now it gets stuck at "Setting up a new session..." then stops
 
What do I do? How can I see the visualization of the results?

**Comment by atheeraa** [comment]
Thank you! 
It works now!

**Comment by HanGuangXin** [comment]
Issue closed.
